version: '3.9'

services:

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      SKYCRUISESETTING_DATABASES: '{"default":{"HOST":"db"}}'
      SKYCRUISESETTING_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql-data:
    driver: local
