# Generated by Django 5.0.6 on 2024-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flight_airline'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_flights',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='flight.flight'),
        ),
    ]
