# Generated by Django 5.0.6 on 2024-05-21 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='passengers',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
