# Generated by Django 5.0.6 on 2024-05-23 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0006_flight_tax_price_flight_travel_insurance_price'),
        ('users', '0006_remove_user_stripe_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')],
                        default='confirmed',
                        max_length=10
                    )
                ),
                (
                    'flight',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flight.flight'
                    )
                ),
                ('passengers', models.ManyToManyField(related_name='reservations', to='users.passenger')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reservations',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
        ),
    ]
