# Generated by Django 5.0.6 on 2024-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
