# Generated by Django 5.0.6 on 2024-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
