# Generated by Django 5.0.6 on 2024-05-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateField(),
        ),
    ]
