# Generated by Django 5.0.6 on 2024-05-20 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
        ('flight', '0003_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airline.airline'
            ),
            preserve_default=False,
        ),
    ]
