# Generated by Django 5.0.6 on 2024-05-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flight_airline'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_status',
            field=models.CharField(
                choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'),
                         ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('arrived', 'Arrived'),
                         ('diverted', 'Diverted'), ('unknown', 'Unknown')],
                default='scheduled',
                max_length=10
            ),
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(blank=True, max_length=10, null=True)),
                ('gate', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.airport')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='arrival_flights',
                to='flight.flightdetails'
            ),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='departure_flights',
                to='flight.flightdetails'
            ),
        ),
    ]
