# Generated by Django 5.0.6 on 2024-05-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_remove_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='tax_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='travel_insurance_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
