# Generated by Django 5.0.6 on 2024-05-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_flight_tax_price_flight_travel_insurance_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStepover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'arrival',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stepover_arrival_flights',
                        to='flight.flightdetails'
                    )
                ),
                (
                    'departure',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stepover_departure_flights',
                        to='flight.flightdetails'
                    )
                ),
                (
                    'flight',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='stepovers', to='flight.flight'
                    )
                ),
            ],
        ),
    ]
