# Generated by Django 5.0.6 on 2024-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_seat_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
