# Generated by Django 5.0.6 on 2024-05-25 07:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='airline_logos'),
            preserve_default=False,
        ),
    ]
